# Leader keys
set -g prefix C-Space
bind C-Space send-prefix # ensure we can still send to other apps

# Set secondary prefix (e.g., Ctrl-b)
set -g prefix2 C-b
bind C-b send-prefix # ensure we can still send to other apps

# Reload key
bind r source-file ~/.tmux.conf \; display 'Reloaded!'

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Navigate windows using Ctrl+Tab and Ctrl+Shift+Tab
bind -n C-Tab select-window -n
bind -n C-S-Tab select-window -p# switch panes using Alt-arrow without prefix

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind k kill-window

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# change number for windows and panes
set -g base-index 1

# don't rename windows automatically
set-option -g allow-rename off

# Setup status bar
set -g status-justify centre
set -g status-left-length 40
set -g status-left "#[fg=green]Session: #S "

# Start window numbering at 1
set -g base-index 1

# Start pane numbering at 1
setw -g pane-base-index 1

# Automatically renumber windows when one is closed
set -g renumber-windows on

######## DESIGN TWEAKS

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour yellow

# copy mode
setw -g mode-style 'fg=black bg=green bold'

# panes
set -g pane-border-style 'fg=green'
set -g pane-active-border-style 'fg=yellow'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=green'

set -g status-right-style 'fg=black bg=green'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=green'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=green bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=green]#F '

setw -g window-status-bell-style 'fg=yellow bg=green bold'

# messages
set -g message-style 'fg=yellow bg=green bold'
